# Generated by Django 4.1.1 on 2022-09-16 02:40

from django.db import migrations, models
import django_resized.forms


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='blog_post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('slug', models.SlugField(unique=True)),
                ('image', django_resized.forms.ResizedImageField(crop=['center'], default='default_image.jpg', force_format=None, keep_meta=True, quality=-1, scale=None, size=[500, 500], upload_to='static/image')),
                ('content', models.TextField(max_length=5000)),
                ('auther', models.CharField(max_length=50)),
                ('post_time', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
