# Generated by Django 4.1.1 on 2022-09-16 02:50

from django.db import migrations
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog_post',
            name='image',
            field=django_resized.forms.ResizedImageField(crop=['middle', 'center'], default='default_image.jpg', force_format=None, keep_meta=True, quality=-1, scale=None, size=[500, 500], upload_to='static/image'),
        ),
    ]
