# Generated by Django 4.1.1 on 2022-09-16 02:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_alter_blog_post_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog_post',
            old_name='auther',
            new_name='author',
        ),
    ]
