# Generated by Django 4.1.1 on 2022-09-19 03:00

from django.db import migrations, models
import django.db.models.deletion
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_alter_blog_post_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='image_category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=200)),
                ('slug', models.SlugField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', django_resized.forms.ResizedImageField(crop=['middle', 'center'], force_format=None, keep_meta=True, quality=-1, scale=None, size=[1000, 1000], upload_to='static/image')),
                ('image_name', models.CharField(max_length=200)),
                ('image_slug', models.SlugField(unique=True)),
                ('image_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.image_category')),
            ],
        ),
    ]
