# Generated by Django 4.1.1 on 2022-09-25 03:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_image_category_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='image_category',
            new_name='category_image',
        ),
    ]
