# Generated by Django 4.1.1 on 2022-09-26 00:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_rename_image_category_image_category_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image_category',
            old_name='slug',
            new_name='category_slug',
        ),
    ]
